# Generated by Django 4.2 on 2026-07-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_key', models.CharField(max_length=100)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='core.tblrole')),
            ],
            options={
                'db_table': 'tbl_role_permission',
                'unique_together': {('role', 'page_key')},
            },
        ),
    ]
