# Generated by Django 4.2 on 2026-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tblrolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblreasoncode',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
