# Generated by Django 4.2 on 2026-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tblproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproduct',
            name='traceability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
