# Generated by Django 4.2 on 2026-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tblproduct_traceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='pass_word',
            field=models.CharField(max_length=255),
        ),
    ]
