# Generated by Django 4.2 on 2026-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tblreasoncode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblreasoncode',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tblreasoncode',
            name='reason_type_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
