# Generated by Django 4.2 on 2026-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tblreasoncode_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproduct',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
