# Generated by Django 4.2 on 2026-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_password_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblresourcelabourdetailmodule',
            name='module_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tblresourcelabourdetailmoduledowntime',
            name='module_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
